config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :houses do
      get 'pictures/upload'
      post '/upload' => 'pictures#create'
      get 'pictures/unlock'
      post '/unlock' => 'pictures#match_unlock'
      get 'pictures/lock'
      post '/lock' => 'pictures#match_lock'
    end
  end
  root 'users#dashboard'

  get '/invite' => 'users#invite'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/house.rb
class House < ActiveRecord::Base
	validates :name, presence: true

	has_many :house_users
	has_many :users, through: :house_users
	has_many :pictures
end

app/models/house_user.rb
class HouseUser < ActiveRecord::Base
	validates :house_id, presence: true
	validates :user_id, presence: true

  belongs_to :house
  belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :image, styles: { large: "400x400" }

  belongs_to :user
  belongs_to :house

  validates_attachment :image, content_type: { content_type: ["image/jpeg", "image/png"]}

  def self.enroll(url, person, house_name)


    body = {:image => url, :subject_id => person, :gallery_name => house_name, :selector => "SETPOSE", :symmetricFill => "true"  }
    body = body.to_json

    headers = {
      'content_type' => 'application/json',
      'app_id' => ENV['KAIROS_ID'],
      'app_key' => ENV['KAIROS_KEY']
    }

    response = HTTParty.post('https://api.kairos.com/enroll', { headers: headers, body: body })
    ap response
  end

  def self.recognize(url, house_name, number, command)

    threshold = '0.80'

    body = {:image => url, :gallery_name => house_name, :threshold => threshold}
    body = body.to_json


    headers = {
      'content_type' => 'application/json',
      'app_id' => ENV['KAIROS_ID'],
      'app_key' => ENV['KAIROS_KEY']
    }

    response = HTTParty.post('https://api.kairos.com/recognize', { body: body, headers: headers})

    ap response

    successtest = response['images'][0]['transaction']['status']
    # ap successtest
    successtest
    command
    Picture.text(successtest, number, command)
  end

  def self.text(status, number, command)
    client = Twilio::REST::Client.new ENV['account_sid'], ENV['auth_token']
    from = '+19546136144'
    if status == 'success'
      if command == 'unlock'
        client.account.messages.create(
        :from => from,
        :to => "+13053262790",
        :body => "unlock"
        )
      else
        if command == 'lock'
          client.account.messages.create(
          :from => from,
          :to => "+13053262790",
          :body => "lock"
          )
        else
          p "face not recognized"
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
	validates :email, presence: true, uniqueness: true
  validates :phone_number, presence: true, uniqueness: true


	has_many :house_users
	has_many :houses, through: :house_users
	has_secure_password

	has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/house_users_controller.rb
class HouseUsersController < ApplicationController
	before_filter :authorize

	
	
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
	before_filter :authorize

	def new
		@house = House.new
	end

	def show
		@house = House.find(params[:id])
	end

	def create
		user = User.find(params[:user_id])
		@house = user.houses.build(house_params)

		respond_to do |format|
			if @house.save
				HouseUser.create(house_id: @house.id, user_id: current_user.id)
				format.html {redirect_to root_path, notice: 'House made'}
			else
				format.html {render :new}
			end
		end
	end

	private

	def house_params
		params.require(:house).permit(:name)
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

	def upload
		@picture = Picture.new

	end

	def create
		user = User.find(params[:user_id])
		house = House.find(params[:house_id])

		if params[:picture][:image]
			params[:picture][:image].each do |image|
				@picture = user.pictures.build(image: image)
				@picture.house_id = house.id
				@picture.save
				person = @picture.user.first_name + " " + @picture.user.last_name
				house_name = @picture.house.name
				url = @picture.image.url
				Picture.enroll(url, person, house_name)
			end
			p 'picture saved'
			redirect_to root_path
		else
			p 'picture didnt save'
		end
	end

	def matchPage
		@picture = Picture.new
	end

	def match_unlock
		user = User.find(params[:user_id])
		house = House.find(params[:house_id])
		if params[:picture][:image][0]
			@picture = user.pictures.build(image: params[:picture][:image][0])
			@picture.house_id = house.id
			@picture.save
			url = @picture.image.url
			house_name = @picture.house.name
			number = current_user.phone_number
      command = "unlock"
			Picture.recognize(url, house_name, number, command)
    	redirect_to root_path
    end
	end

  def match_lock
		user = User.find(params[:user_id])
		house = House.find(params[:house_id])
		if params[:picture][:image][0]
			@picture = user.pictures.build(image: params[:picture][:image][0])
			@picture.house_id = house.id
			@picture.save
			url = @picture.image.url
			house_name = @picture.house.name
			number = current_user.phone_number
      command = "lock"
			Picture.recognize(url, house_name, number, command)
    	redirect_to root_path
    end
	end

  private

  def pic_params
  	params.require(:picture).permit(:image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
  def new
  end

  def create
  	user = User.find_by_email(params[:email])

  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
      redirect_to '/'
    else
    	redirect_to '/login'
    end
  end

  def destroy
  	session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, except: [:new, :create]

  # GET /users
  # GET /users.json
  def dashboard
    @user = User.find(current_user)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to '/', notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def invite

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :phone_number, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/house_helper.rb
module HouseHelper
end

app/helpers/house_user_helper.rb
module HouseUserHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/houses/new.html.erb
<h2>Create new house</h2>

<%= form_for :house, url: user_houses_path(current_user.id) do |f| %>

	<div>
		<%= f.label :name %> <br>
		<%= f.text_field :name %>
	</div>
	
	<div>
		<%= f.submit 'Create House' %>
	</div>

<% end %>

app/views/houses/show.html.erb
<h1><%= @house.name.split.map(&:capitalize)*' ' %> Members</h1>

<ul>
	<% @house.users.each do |user| %>
	<li><%= user.first_name %> <%= user.last_name %> | <%= link_to 'Add face', user_house_pictures_upload_path(user.id, @house.id) %></li>
	<% end %>
</ul>

<%= link_to 'back to profile', controller: 'users', action: 'dashboard' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peek</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  Signed in as <%= current_user.first_name %> <%= current_user.last_name %> | <%= link_to "Logout", '/logout' %>
<% else %>
  <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
<% end %>

<%= yield %>

</body>
</html>

app/views/pictures/lock.html.erb
<h1>Lock</h1>

<%= form_for @picture, url: user_house_lock_path, html: {multipart: true} do |f| %>
  <p>
    <%= f.file_field :image, type: :file, multiple: true %>
  </p>

  <%= f.submit 'Lock' %>
<% end %>

<%= link_to 'back to profile', controller: 'users', action: 'dashboard' %>

app/views/pictures/unlock.html.erb
<h1>Unlock</h1>

<%= form_for @picture, url: user_house_unlock_path, html: {multipart: true} do |f| %>
  <p>
    <%= f.file_field :image, type: :file, multiple: true %>
  </p>

  <%= f.submit 'Unlock' %>
<% end %>

<%= link_to 'back to profile', controller: 'users', action: 'dashboard' %>

app/views/pictures/upload.html.erb
<h1>Add Pictures for Facial Recognition</h1>

<%= form_for @picture, url: user_house_upload_path, html: {multipart: true} do |f| %>
  <p>
    <%= f.file_field :image, type: :file, multiple: true %>
  </p>
  <p>
    <%= f.file_field :image, type: :file, multiple: true %>
  </p>
  <p>
    <%= f.file_field :image, type: :file, multiple: true %>
  </p>

  	<%= f.submit 'Send pictures' %>
<% end %>

<%= link_to 'back to profile', controller: 'users', action: 'dashboard' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/dashboard.html.erb
<h1>Welcome to the Dashboard</h1>

<h2>Your Houses</h2>
<h4>Click a house to view members</h4>
<ul>
<% @user.houses.each do |house| %>
	<li><%= house.name.split.map(&:capitalize)*' ' %> | <%= link_to 'manage house', user_house_path(current_user.id, house.id) %> | <%= link_to 'unlock house', user_house_pictures_unlock_path(current_user.id, house.id) %>| <%= link_to 'lock house', user_house_pictures_lock_path(current_user.id, house.id) %></li>
<% end %>
</ul>

<%= link_to 'Add new house', new_user_house_path(current_user.id) %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

	<div>
	<%= f.label :first_name %> <br>
  <%= f.text_field :first_name %>
  </div>
  <div>
  	<%= f.label :last_name %> <br>
  	<%= f.text_field :last_name %>
  </div>
  <div>
  	<%= f.label :phone_number %> <br>
  	<%= f.telephone_field :phone_number %>
  </div>
  <div>
	<%= f.label :email %> <br>
	<%= f.text_field :email %>
	</div>
	<div>
	<%= f.label :password %> <br>
  <%= f.password_field :password %>
  </div>
  <div>
	<%= f.label :password_confirmation %> <br>
	<%= f.password_field :password_confirmation %>
	</div>
	<div>
  <%= f.submit "Submit" %>
  </div>

<% end %>

<%= link_to 'Back', login_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>